### ISSUE TITLE
Update for autoit_ripper - [not really an issue]

### ISSUE THREAD

**Issue by Hopfengetraenk** [nazywam/AutoIt-Ripper#7]
Well I did some work on the sources.
However I don't get it done to issue a pull request for that so I just add the files here:
[autoit_ripper_Dec2020.zip](https://github.com/nazywam/AutoIt-Ripper/files/5762303/autoit_ripper_Dec2020.zip)
If someone can push these into that repo it would be nice.

Some of the changes:
* added support for newer opcode 0x00 and 0x01 tokens
* restore case for keywords
* speed up decryption

**Comment by JL1829** [comment]
How can we use it? Anyway document to make it run?

**Comment by nazywam** [comment]
```python
# self.data = self.data[num:] # Fucking slow !!!
```

Extremely good catch there 😅

**Comment by PikuZheng** [comment]
```
from utils import myBinaryReader, myScriptReader
```
what's myBinaryReader, myScriptReader?

**Comment by nazywam** [comment]
Thanks again!
